### ISSUE TITLE
After build apk with this plugin I have next issue from Huawei review team - "your App is detected to carry virus: Android:Cynos-BI [Spy]||mult."

### ISSUE THREAD

**Issue by devaliarshad** [EvilMindDevs/hms-unity-plugin#241] opened 2021-12-07 10:03 UTC

**Comment by sametguzeldev** [comment] 2021-12-07 10:07
Duplicate of #235. We are looking into it.

**Comment by devaliarshad** [comment] 2021-12-07 13:45
@sametguzeldev thanks let me check

**Comment by sametguzeldev** [comment] 2021-12-08 23:25
Fixed in 2.0.15 version.

**Closed by sametguzeldev** 2021-12-08 23:25 UTC
Labels: duplicate
