### ISSUE TITLE
Push Kit Error

### ISSUE THREAD

**Issue by chinmaygawande123** [EvilMindDevs/hms-unity-plugin#176] opened 2021-09-02 08:32 UTC
When I am Building Project with Push Kit this error pops up : 

Could not find file "/Users/admin/Downloads/AR Multi Vuforia copy/Temp/gradleOut/unityLibrary\src\main\java\com\unity3d\player\UnityPlayerActivity.java"

And Console Shows This Error : 

FileNotFoundException: Could not find file "/Users/admin/Downloads/AR Multi Vuforia copy/Temp/gradleOut/unityLibrary\src\main\java\com\unity3d\player\UnityPlayerActivity.java"
System.IO.FileStream..ctor (System.String path, System.IO.FileMode mode, System.IO.FileAccess access, System.IO.FileShare share, System.Int32 bufferSize, System.Boolean anonymous, System.IO.FileOptions options) (at <695d1cc93cca45069c528c15c9fdd749>:0)
System.IO.FileStream..ctor (System.String path, System.IO.FileMode mode, System.IO.FileAccess access, System.IO.FileShare share) (at <695d1cc93cca45069c528c15c9fdd749>:0)
(wrapper remoting-invoke-with-check) System.IO.FileStream..ctor(string,System.IO.FileMode,System.IO.FileAccess,System.IO.FileShare)
HMSGradleFixer.OnPostGenerateGradleAndroidProject (System.String path) (at Assets/Huawei/Editor/Utils/HMSGradleFixer.cs:42)
UnityEditor.Android.AndroidBuildPipelineInterfaces.OnGeneratePlatformProjectPostprocess (System.String path, System.Boolean strict) (at /Users/bokken/buildslave/unity/build/Editor/Mono/BuildPipeline/Android/AndroidPostGenerateGradleProject.cs:45)
UnityEditor.Android.PostProcessor.Tasks.ExportProject.Execute (UnityEditor.Android.PostProcessor.PostProcessorContext context) (at <1f5aacfb83804e518b48285b5fe58926>:0)
Rethrow as BuildFailedException: Exception of type 'UnityEditor.Build.BuildFailedException' was thrown.
UnityEditor.Android.PostProcessor.CancelPostProcess.AbortBuild (System.String title, System.String message, System.Exception ex) (at <1f5aacfb83804e518b48285b5fe58926>:0)
UnityEditor.Android.PostProcessor.Tasks.ExportProject.Execute (UnityEditor.Android.PostProcessor.PostProcessorContext context) (at <1f5aacfb83804e518b48285b5fe58926>:0)
UnityEditor.Android.PostProcessor.PostProcessRunner.RunAllTasks (UnityEditor.Android.PostProcessor.PostProcessorContext context) (at <1f5aacfb83804e518b48285b5fe58926>:0)
UnityEditor.Android.PostProcessAndroidPlayer.PostProcess (UnityEditor.BuildTarget target, System.String stagingAreaData, System.String stagingArea, System.String playerPackage, System.String installPath, System.String companyName, System.String productName, UnityEditor.BuildOptions options, UnityEditor.RuntimeClassRegistry usedClassRegistry, UnityEditor.Build.Reporting.BuildReport report) (at <1f5aacfb83804e518b48285b5fe58926>:0)
UnityEditor.Android.AndroidBuildPostprocessor.PostProcess (UnityEditor.Modules.BuildPostProcessArgs args, UnityEditor.BuildProperties& outProperties) (at <1f5aacfb83804e518b48285b5fe58926>:0)
UnityEditor.PostprocessBuildPlayer.Postprocess (UnityEditor.BuildTargetGroup targetGroup, UnityEditor.BuildTarget target, System.String installPath, System.String companyName, System.String productName, System.Int32 width, System.Int32 height, UnityEditor.BuildOptions options, UnityEditor.RuntimeClassRegistry usedClassRegistry, UnityEditor.Build.Reporting.BuildReport report) (at /Users/bokken/buildslave/unity/build/Editor/Mono/BuildPipeline/PostprocessBuildPlayer.cs:337)
UnityEditor.BuildPlayerWindow:BuildPlayerAndRun() (at /Users/bokken/buildslave/unity/build/Editor/Mono/BuildPlayerWindow.cs:123)

**Comment by sametguzeldev** [comment] 2021-09-02 08:34
Hello there.
Which version of Unity and which version of HMS Unity Plugin are you using?

**Comment by chinmaygawande123** [comment] 2021-09-02 09:09
Unity :  2020.3.14f1
HMS :  2.0.9

**Comment by chinmaygawande123** [comment] 2021-09-02 09:10
Unity :  2020.3.14f1
HMS :  2.0.9

**Comment by sametguzeldev** [comment] 2021-09-02 21:24
I have tried it with your version but I could not re-produce the issue sadly.

**Comment by chinmaygawande123** [comment] 2021-09-05 05:42
Error is still persistent.

**Comment by sametguzeldev** [comment] 2021-09-09 07:44
Can you reproduce the issue on an empty project? Because I cannot really reproduce this error.

**Comment by incadawr** [comment] 2021-09-16 09:37
Same error when i tried to build on linux platform.

I fixed it by changing this row:
`     string unityPlayerActivityJavaPath = path + @"\src\main\java\com\unity3d\player\UnityPlayerActivity.java"; `
to
`     string unityPlayerActivityJavaPath = path + @"/src/main/java/com/unity3d/player/UnityPlayerActivity.java"; `

I guess, you should use `Path.DirectorySeparatorChar` for avoiding such issues.

**Comment by sametguzeldev** [comment] 2021-09-16 10:55
> Same error when i tried to build on linux platform.
> 
> I fixed it by changing this row:
> ` string unityPlayerActivityJavaPath = path + @"\src\main\java\com\unity3d\player\UnityPlayerActivity.java";`
> to
> ` string unityPlayerActivityJavaPath = path + @"/src/main/java/com/unity3d/player/UnityPlayerActivity.java";`
> 
> I guess, you should use `Path.DirectorySeparatorChar` for avoiding such issues.

That's a good idea! I will make this change for the new version.

**Comment by sametguzeldev** [comment] 2021-10-05 08:16
Fixed in #193.

**Closed** 2021-10-05 08:18 UTC
