### ISSUE TITLE
Functional demo missing

### ISSUE THREAD

**Issue by EtsaiDev** [EvilMindDevs/hms-unity-plugin#8] opened 2020-05-15 14:34 UTC
Hi,
the fully functional demo for all available kits was scheduled for yesterday but the last released unity package does not include any demo. I tried to create my IAP system with the given files but the code seems to be unfinished and not functional. Is the old undiscontinued version of Unity HMS plugin working? should I work with that and wait until this new branch is completed?
Thank you!

**Comment by EvilMindDevs** [comment] 2020-05-15 15:03
Hi,
Demos still WIP, we couldnt meet our estimations since we had to fix some unexpected bugs. Hope to have the demos uploaded next week.

IapManager is working, you can try that and we'll upload demos soon.

**Comment by m0skit0** [comment] 2020-06-17 14:37
Duplicate of #5

**Closed by m0skit0** 2020-06-17 14:37 UTC
Labels: documentation
