### ISSUE TITLE
FileNotFoundException AndroidManifest.xml does not exist

### ISSUE THREAD

**Issue by WrobelKrakow** [EvilMindDevs/hms-unity-plugin#9] opened 2020-05-19 13:58 UTC
When i want to save editor window, I had this error: 
`FileNotFoundException: C:\UnityInstalls\2019.3.13f1\Editor\Data\PlaybackEngines\AndroidPlayer\Apk\AndroidManifest.xml does not exist

System.IO.File.Copy (System.String sourceFileName, System.String destFileName, System.Boolean overwrite) (at <437ba245d8404784b9fbab9b439ac908>:0)
System.IO.File.Copy (System.String sourceFileName, System.String destFileName) (at <437ba245d8404784b9fbab9b439ac908>:0)

HuaweiEditor.prepareManifest () (at Assets/Huawei/Scripts/Editor/HuaweiEditor.cs:161)
HuaweiEditor.OnGUI () (at Assets/Huawei/Scripts/Editor/HuaweiEditor.cs:95)`

As workaround I created manifest.xml file in plugins/Android

**Comment by m0skit0** [comment] 2020-05-22 14:09
Cannot reproduce this. Can you please specify which Unity version gives you this error?

Please note that `AndroidManifest.xml` does exist under `hms-unity-plugin\Assets\Plugins\Android`, you can check in the project repo.

**Comment by EvilMindDevs** [comment] 2020-05-22 15:21
In 2019 version , default manifest changed name to UnityManifest.
Fixed on commit d309b382b8fa39d11982746501fde23e65cd8aa8

**Closed by EvilMindDevs** 2020-05-22 15:21 UTC
